version: "3.0"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      ["wait-for-it", "db:3306", "-t", "30", "--", "/docker/start_app.sh"]
    volumes:
      - ./webapp:/webapp
    cap_add:
      - CAP_SYS_ADMIN
    ports:
      - "8081:8080"
    # for flamegraph outputh
    stop_grace_period: 5m
    container_name: isucon_app
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: isucon
      MYSQL_DATABASE: isuumo
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
    ports:
      - 13306:3306
    volumes:
      - ./docker/mysql:/var/lib/mysql
    container_name: isucon_db
volumes:
  storage_app:
