#!/bin/bash

set -v

root=$(cd "$(dirname "$0")" && cd .. && pwd)
now=$(date +%Y%m%d-%H%M%S)

branch=${1-master}

command="source ~/.bashrc && cd /home/isucon/ISUCON-2020-qualify/webapp/rust && git remote update && git checkout $branch && git pull && make build && sudo systemctl restart isuumo.rust"
rotate_nginx="sudo mv /var/log/nginx/access.log /var/log/nginx/access.log.$now && sudo ln -sf /var/log/nginx/access.log.$now /var/log/nginx/access.log.latest; sudo systemctl reload nginx.service"
rotate_mysql="sudo mv /var/log/mysql/slow.log /var/log/mysql/slow.log.$now && sudo ln -sf /var/log/mysql/slow.log.$now /var/log/mysql/slow.log.latest; mysqladmin -uishocon -pishocon flush-logs"

ssh isu1 "$command"

ssh isu1 "$rotate_nginx"
ssh isu1 "$rotate_mysql"
